// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: BiDirectionalStreaming/findMaximumApi/proto/max.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MaximumApiClient is the client API for MaximumApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MaximumApiClient interface {
	// BiDi Streaming
	FindMaximum(ctx context.Context, opts ...grpc.CallOption) (MaximumApi_FindMaximumClient, error)
}

type maximumApiClient struct {
	cc grpc.ClientConnInterface
}

func NewMaximumApiClient(cc grpc.ClientConnInterface) MaximumApiClient {
	return &maximumApiClient{cc}
}

func (c *maximumApiClient) FindMaximum(ctx context.Context, opts ...grpc.CallOption) (MaximumApi_FindMaximumClient, error) {
	stream, err := c.cc.NewStream(ctx, &MaximumApi_ServiceDesc.Streams[0], "/ClientStreaming.MaximumApi/findMaximum", opts...)
	if err != nil {
		return nil, err
	}
	x := &maximumApiFindMaximumClient{stream}
	return x, nil
}

type MaximumApi_FindMaximumClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type maximumApiFindMaximumClient struct {
	grpc.ClientStream
}

func (x *maximumApiFindMaximumClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *maximumApiFindMaximumClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MaximumApiServer is the server API for MaximumApi service.
// All implementations must embed UnimplementedMaximumApiServer
// for forward compatibility
type MaximumApiServer interface {
	// BiDi Streaming
	FindMaximum(MaximumApi_FindMaximumServer) error
	mustEmbedUnimplementedMaximumApiServer()
}

// UnimplementedMaximumApiServer must be embedded to have forward compatible implementations.
type UnimplementedMaximumApiServer struct {
}

func (UnimplementedMaximumApiServer) FindMaximum(MaximumApi_FindMaximumServer) error {
	return status.Errorf(codes.Unimplemented, "method FindMaximum not implemented")
}
func (UnimplementedMaximumApiServer) mustEmbedUnimplementedMaximumApiServer() {}

// UnsafeMaximumApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MaximumApiServer will
// result in compilation errors.
type UnsafeMaximumApiServer interface {
	mustEmbedUnimplementedMaximumApiServer()
}

func RegisterMaximumApiServer(s grpc.ServiceRegistrar, srv MaximumApiServer) {
	s.RegisterService(&MaximumApi_ServiceDesc, srv)
}

func _MaximumApi_FindMaximum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MaximumApiServer).FindMaximum(&maximumApiFindMaximumServer{stream})
}

type MaximumApi_FindMaximumServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type maximumApiFindMaximumServer struct {
	grpc.ServerStream
}

func (x *maximumApiFindMaximumServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *maximumApiFindMaximumServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MaximumApi_ServiceDesc is the grpc.ServiceDesc for MaximumApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MaximumApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ClientStreaming.MaximumApi",
	HandlerType: (*MaximumApiServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "findMaximum",
			Handler:       _MaximumApi_FindMaximum_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "BiDirectionalStreaming/findMaximumApi/proto/max.proto",
}
